apiVersion: v1
kind: Service

metadata:
  name: authservice
  namespace: credit-card-app

spec:
  selector:
    app: authservice

  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

  type: ClusterIP