apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: credit-card-app
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP
