apiVersion: v1
kind: Service

metadata:
  namespace: credit-card-app
  name: frontend

spec:
  selector:
    label:
      app: frontend

  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

  type: ClusterIP