apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-secret
  namespace: monitoring
type: Opaque
stringData:
  webhook-url: "https://discord.com/api/webhooks/1539091819160272997/XKOLXmM2cNsYyPg5waA_LUjsuusERBQg4cdAm9_a8WGXqr2eAAA0UeVa9m80j9vprqyf"
