apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-card-config
  namespace: credit-card-app

data:
  AUTH_PORT: "8001"
  APPLICATION_PORT: "8002"
  DECISION_PORT: "8003"
  DB_PORT: "5432"

  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "60"