apiVersion: v1
kind: Secret

metadata:
  namespace: credit-card-app
  name: credit-card-secret

type: Opaque

stringData:


  JWT_SECRET_KEY: "replace_with_a_long_random_secret"

  AUTH_DATABASE_URL: "postgresql+asyncpg://ccapp:change_me_strong_password@postgres:5432/auth_db"
  APPLICATION_DATABASE_URL: "postgresql+asyncpg://ccapp:change_me_strong_password@postgres:5432/application_db"
  DECISION_DATABASE_URL: "postgresql+asyncpg://ccapp:change_me_strong_password@postgres:5432/decision_db"