apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: credit-card-app
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: "Y2hhbmdlX21lX3N0cm9uZ19wYXNzd29yZA==" # This is the base64 encoded value of "change_me_strong_password". You can change it to your desired password and encode it in base64 format.