apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: credit-card-app
  labels: 
    app: postgres
data:
   init.sql: |
      CREATE DATABASE application_db;
      CREATE DATABASE decision_db;
      CREATE DATABASE auth_db;
      
     
    