apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationservice
  namespace: credit-card-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicationservice
  template:
    metadata:
      labels:
        app: applicationservice
    spec:
      containers:
        - name: applicationservice
          image: pranjal261/credit-card-application-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: credit-card-secrets
                  key: APPLICATION_DATABASE_URL

            - name: CREDIT_DECISION_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: credit-card-secrets
                  key: DECISION_DATABASE_URL

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: credit-card-secrets
                  key: JWT_SECRET_KEY

            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: credit-card-config
                  key: JWT_ALGORITHM

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: credit-card-config
                  key: APPLICATION_PORT

             
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
