apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: credit-card-app
spec:
  selector:
    app: applicationservice
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP  