apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: credit-card-app
  name: credit-decision

spec:
  replicas: 2

  selector:
    matchLabels:
      app: credit-decision

  template:
    metadata:
      name: credit-decision
      label:
        app: credit-decision

    spec:
      containers:
        - name: credit-decision
          image: pranjal261/credit-card-decision-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8003

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: credit-card-config
                  key: DECISION_PORT

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: credit-card-secrets
                  key: DECISION_DATABASE_URL
          

          resources:
            request:
              cpu: "100m"
              memory: "128Mi"

            limit:
              cpu: "200m"
              memory: "256Mi"
            
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 10

