apiVersion: apps/v1
kind: Deployment
metadata:
  name: decision
  namespace: credit-card-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decision
  template:
    metadata:
      labels:
        app: decision
    spec:
      containers:
        - name: decision
          image: pranjal261/credit-card-decision-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: decision-config
            - secretRef:
                name: decision-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5
