apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: decision-service-monitor
  namespace: credit-card-app
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: decision
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
