apiVersion: v1
kind: Service
metadata:
  name: decision-service
  namespace: credit-card-app

spec:
  type: ClusterIP

  selector:
    app: credit-decision

  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
