name: Frontend Service CI/CD

on:
  push:
    branches:
      - eks_test
    paths:
      - "frontend/**"

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: credit-card-eks
  K8S_NAMESPACE: credit-card-app
  K8S_DEPLOYMENT: frontend
  K8S_CONTAINER: frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4


      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json


      # 3. Install frontend dependencies
      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm ci


      # 4. Build Angular frontend
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm run build


      # 5. Run Linting
      - name: Run Lint
        working-directory: ./frontend
        run: |
          npm run lint


      # 6. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # 7. Build Docker image
      - name: Build Docker image
        run: |
          docker build --pull \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/credit-card-frontend:${{ github.sha }} \
            ./frontend


      # 8. Scan Docker image with Trivy
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/credit-card-frontend:${{ github.sha }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: CRITICAL,HIGH


      # 9. Push Docker image to Docker Hub
      # This runs ONLY if Trivy passes.
      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/credit-card-frontend:${{ github.sha }}


      # 10. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      # 11. Verify AWS identity
      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity


      # 12. Configure kubectl for EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.EKS_CLUSTER_NAME }}


      # 13. Verify EKS connection
      - name: Verify EKS connection
        run: |
          kubectl get nodes
          kubectl get pods -n ${{ env.K8S_NAMESPACE }}


      # 14. Update frontend image in Kubernetes
      - name: Update frontend deployment
        run: |
          kubectl set image deployment/${{ env.K8S_DEPLOYMENT }} \
            ${{ env.K8S_CONTAINER }}=${{ secrets.DOCKERHUB_USERNAME }}/credit-card-frontend:${{ github.sha }} \
            -n ${{ env.K8S_NAMESPACE }}


      # 15. Check Kubernetes rollout
      - name: Check rollout status
        run: |
          kubectl rollout status \
            deployment/${{ env.K8S_DEPLOYMENT }} \
            -n ${{ env.K8S_NAMESPACE }} \
            --timeout=5m


      # 16. Show final deployment status
      - name: Show deployment status
        run: |
          echo "Deployment:"
          kubectl get deployment \
            ${{ env.K8S_DEPLOYMENT }} \
            -n ${{ env.K8S_NAMESPACE }}

          echo "-------------------------------"

          echo "Pods:"
          kubectl get pods \
            -n ${{ env.K8S_NAMESPACE }}
