name: Security Scan

on:
  push:
    branches:
      - eks_test

  pull_request:
    branches:
      - eks_test

permissions:
  contents: read

jobs:
  gitleaks:
    name: Gitleaks secret scan
    runs-on: ubuntu-latest

  steps:
    
    # 1. Checkout the entire repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Scan repository for leaked secrets
      - name: GitLeaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
